import FullLayout from "../src/layouts/FullLayout";
import Head from "next/head";
import "../styles/style.scss";
// import "../src/components/dashboard/Login/login.css";


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Xtreme Starter Next Js App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      {/* <FullLayout> */}
        <Component {...pageProps} />
      {/* </FullLayout> */}
    </>
  );
}

export default MyApp;
